### ISSUE TITLE
Cannot login after clean install

### ISSUE THREAD

**Issue by iccaprar** [hazelcast/hazelcast-docker-samples#17]
Hi,

I installed the sample with the management console JAAS provider, everything starts, but then trying to login with the admin user results in the error "Access denied! User has no roles!" in the browser and in the console I see "management-center_1  | 2019-05-03 11:34:45 [qtp1485955886-14] WARN  c.h.w.s.s.i.AccessDeniedHandlerImpl - Access denied. Logging out:".

Startup console:
`Starting management-center-jaas_management-center_1 ... done
Attaching to management-center-jaas_management-center_1
management-center_1  | ########################################
management-center_1  | # JAVA_OPTS=-Dhazelcast.mancenter.home=/data -Djava.net.preferIPv4Stack=true
management-center_1  | # starting now....
management-center_1  | ########################################
management-center_1  | + exec java --add-opens java.base/java.lang=ALL-UNNAMED -server -Dhazelcast.mancenter.home=/data -Djava.net.preferIPv4Stack=true -jar /opt/hazelcast/mancenter/hazelcast-mancenter-3.12.war 8080 8443 hazelcast-mancenter
management-center_1  | 2019-05-03 11:16:30 [main] INFO  c.h.webmonitor.config.BuildInfo - Management Center 3.12
management-center_1  | 2019-05-03 11:16:33 [main] INFO  c.h.w.storage.DiskUsageMonitor - Monitoring /data [mode=purge, interval=1000ms, limit=512 MB]
management-center_1  | 2019-05-03 11:16:42 [main] INFO  c.h.w.s.s.impl.DisableLoginStrategy - Login will be disabled for 5 seconds after 3 failed login attempts. For every 3 consecutive failed login attempts, disable period will be multiplied by 10.
management-center_1  | 2019-05-03 11:16:42 [main] INFO  c.h.webmonitor.config.SqlDbConfig - Checking DB for required migrations.
management-center_1  | 2019-05-03 11:16:43 [main] INFO  c.h.webmonitor.config.SqlDbConfig - Number of applied DB migrations: 1.
management-center_1  | Hazelcast Management Center successfully started at http://localhost:8080/hazelcast-mancenter`

I never got the security configuration screen mentioned in the management console docs.

I opened a shell into the running docker container and checked the contents of the /data folder. 

`root@0fa29724c702:/data# ls -al
total 264
drwxrwxrwx 3 root root  4096 May  3 11:16 .
drwxr-xr-x 1 root root  4096 May  3 11:06 ..
-rw-r--r-- 1 root root     0 May  3 11:16 alert.db
-rw-r--r-- 1 root root 41361 May  3 11:16 alert.lg
-rw-r--r-- 1 root root     0 May  3 11:16 alertFilterConfig.db
-rw-r--r-- 1 root root 41361 May  3 11:16 alertFilterConfig.lg
-rw-r--r-- 1 root root     0 May  3 11:16 email.db
-rw-r--r-- 1 root root 41361 May  3 11:16 email.lg
-rw-r--r-- 1 root root   205 May  3 10:20 jaas.properties
-rw-r--r-- 1 root root     0 May  3 11:16 mc.lock
-rw-r--r-- 1 root root     0 May  3 11:16 script.db
-rw-r--r-- 1 root root 41361 May  3 11:16 script.lg
-rw-r--r-- 1 root root    21 May  3 10:20 security.properties
drwxr-xr-x 2 root root  4096 May  3 11:16 sql
-rw-r--r-- 1 root root     0 May  3 11:16 user.db
-rw-r--r-- 1 root root 66208 May  3 11:16 user.lg`

Tried to remove everything from there and restart:
- cannot remove security.properties as it is used
- cannot remove jaas.properties as it is used

`root@0fa29724c702:/data# cat security.properties 
currentProvider=JAAS`

`root@0fa29724c702:/data# cat jaas.properties 
#Management center JAAS configuration
readonlyUserGroup=MancenterReadonlyUser
loginModuleClass=SampleLoginModule
metricsOnlyGroup=MancenterMetricsOnlyUser
adminGroup=MancenterAdmin
userGroup=MancenterUser `

What could be wrong?

Thank you!

**Comment by puzpuzpuz** [comment]
Thanks for reporting this issue! It should be fixed soon.

> I never got the security configuration screen mentioned in the management console docs.

That's because the JAAS sample includes a predefined security provider configuration.

**Comment by iccaprar** [comment]
Thank you.
