### ISSUE TITLE
When trying to run the image it complains about ./mc-conf.sh file missing

### ISSUE THREAD

**Issue by rabac** [hazelcast/hazelcast-docker-samples#24]
bash: line 1: ./mc-conf.sh: No such file or directory

**Comment by erosb** [comment]
Hello @rabac ,

thank you for opening this issue. Which docker image do you refer to? I tried out the following and MC started up successfully:

```bash
cd management-center-built-in-user
docker build -t mc-built-in-user .
docker run -p 8080:8080 mc-built-in-user 
```

**Comment by SirSkaro** [comment]
I'm having the same problem. 

```
> docker run -e MC_INIT_CMD="./mc-conf.sh cluster add -H=/data -ma <my-local-ip>:5701 -cn dev" -p 8078:8080 hazelcast/management-center:latest
Container support enabled. Using automatic heap sizing. JVM will use up to 80% of the memory limit of the container.
Executing command specified by MC_INIT_CMD for container initialization.
./bin/mc-start.sh: line 37: ./mc-conf.sh: No such file or directory
```

I get the same result when I use the tag `4.2021.06`.

**Comment by erosb** [comment]
Hello @SirSkaro , thank you for submitting a reproducer. Indeed the correct path of the script is `./bin/mc-conf.sh`. We will fix it the documentation.
